apiVersion: v1
kind: Service
metadata:
  name: toy-music-backend
  namespace: toy-music
spec:
  selector:
    app: toy-music-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30769
  type: NodePort
