apiVersion: apps/v1
kind: Deployment
metadata:
  name: toy-music-frontend
  namespace: toy-music
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toy-music-frontend
  template:
    metadata:
      labels:
        app: toy-music-frontend
    spec:
      containers:
        - name: frontend
          image: toy-music-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
