apiVersion: v1
kind: Service
metadata:
  name: toy-music-frontend
  namespace: toy-music
spec:
  type: NodePort
  selector:
    app: toy-music-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30303
