apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: toy-music
type: Opaque
stringData:
  POSTGRES_DB: your_database_name
  POSTGRES_USER: your_username
  POSTGRES_PASSWORD: your_strong_password_here
